server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    properties:
      jdbc:
        time_zone: UTC
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      authentication-database: admin
      database: comsultant
  mail:
    host: smtp.gmail.com
    port: 587
    username: 구글이메일
    password: 구글비밀번호
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
logging:
  file:
    name: logs/app.log
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] %clr([%M]){cyan}  %clr(%-5level) %clr(%logger{36}){magenta} - %msg%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] [%M] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "logs/app.%d{yyyy-MM-dd}.%i.log"
      max-file-size: 10MB
  level:
    root: WARN
    com.comsultant: debug
response:
  success: success
  fail: fail
expire-time:
  authEmail: 300000
  authorizedEmail: 1800000
  passwordToken: 300000
jwt:
  secret-key: sl14Aelf52Bzk4t35aBkuh1
  access-token-expire-time: 1800000
  refresh-token-expire-time: 1209600000
frontend:
  url: https://j7a602.p.ssafy.io
const:
  password-token-length: 12
  email-auth-length: 6
  comment-list-size: 10
  wish-list-size: 10
  product-list-size: 10
  builder-list-size: 10
social:
  naver-client-id: "네이버 클라이언트 아이디"
  naver-client-secret: "네이버 클라이언트 시크릿"
  naver-api-url: https://openapi.naver.com/v1/nid/me
  naver-state: comstate
  kakao-client-id: "카카오 클라이언트 아이디"
  kakao-client-secret: "카카오 클라이언트 시크릿"
  kakao-api-url: https://kapi.kakao.com/v2/user/me
  google-client-id: "구글 클라이언트 아이디"
  google-client-secret: "구글 클라이언트 시크릿"
  google-callback-url: https://j7a602.p.ssafy.io/social/google
  google-api-url: https://www.googleapis.com/oauth2/v3/userinfo