server:
  port: 8081

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: tester
      enable-auto-commit: false
      auto-offset-reset: earliest


hdfs:
  uri: "hdfs://localhost:9000"
  file-name: "test.txt"