server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comsultant?serverTimezone=UTC&useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=utf8
    username: ssafy
    password: ssafy
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      jdbc:
        time_zone: UTC
  mail:
    host: smtp.gmail.com
    port: 587
    username: comsultant.org@gmail.com
    password: bevrytkzlbkukfnq
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  redis:
    host: localhost
    port: 6379
logging:
  file:
    name: logs/app.log
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] %clr([%M]){cyan}  %clr(%-5level) %clr(%logger{36}){magenta} - %msg%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] [%M] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "logs/app.%d{yyyy-MM-dd}.%i.log"
      max-file-size: 10MB
  level:
    root: WARN
    org.hibernate.type.descriptor.sql: trace
    com.comsultant: debug
response:
  success: success
  fail: fail
expire-time:
  authEmail: 300000
  authorizedEmail: 1800000

